# NumPy
- NumPy is a python library, it is short for "Numerical Python"
- NumPy is used for working with arrays.
- NumPy was created in 2005 by __Travis Oliphant__ . It is an open source project and we can use it freely.



## Why use NumPy? 
-> In python we have lists that serve the purpose of arrays, but they are slow to process.
-> NumPy aims to provide an array object that is up to __50x__ faster than traditional Python List.
-> The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.


# Data Science 
It is the branch of computer science where we study how to store, use and analyze data for deriving information from it.


## Why is NumPy faster than list ?
- NumPy arrays are stored at one continous place in memory unlike lists, so processors can access and manipulate them very effeciently.
- This behaviour is called locality of reference in computer science
    - __In short, locality of reference is the tendency of a processor to access the same set of memory locations repetitively over a short period of time.__
- Also it is optimized to work with latest cpu architechtures.


# Which language is NumPy written in ? 
NumPy is a python library and is written partially in python, but most of the parts that require fast computation are written in C/C++


# Installatin of NumPy
Install NumPy using pip command.

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Import NumPy


In [7]:
import numpy 

arr = numpy.array([1,4,3,2,8,17])
print(arr)

[ 1  4  3  2  8 17]


# NumPy as np
NumPy is usually imported under the np alias

__alias__ = In python alias are an alternate name for referring to the same thing.


In [8]:
import numpy as np

arr = np.array([12,29,2025])
print(arr)


[  12   29 2025]


## Checking NumPy version.
The version string is stored under __version__ attribute.

In [9]:
print(np.__version__)


2.4.2


# Create a NumPy nd array object
we can create a NumPy ndarray object using the array() function.

In [10]:
arr = np.array([98,45,23,11])
print(arr)
print(type(arr))


[98 45 23 11]
<class 'numpy.ndarray'>


# Dimensions in Arrays.
A dimension in arrays is one level of array depth(nested arrays).

nested arrays: arrays that have arrays as their elements.

# 0-D Arrays
0-D arrays or scalars are the elements in an array each value in an array is a 0-D array.

In [11]:
arr = np.array(17)
print(arr)


17


# 1-D Arrays
- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
- These are the most common and basic arrays.

In [12]:
arr = np.array([5,7,8,1])
print(arr)


[5 7 8 1]


# 2-D Arrays
- An array that has 1-D arrays as its elements is called a 2-D Array.
- These are often used to represent matrix or 2nd order tensors.
    - __tensors__ : In simple terms, a tensor is a mathematical object that acts as a generalized container for data. You can think of it as the "big brother" to scalars, vectors, and matrices.


In [13]:
arr = np.array([[1,2,3],[5,6,7]])
print(arr)


[[1 2 3]
 [5 6 7]]


### NumPy has a whole sub module dedicated towards matrix operations called __numpy.mat__ 


# 3-D Arrays
An array that has 2-D arrays as its elements is called 3-D array.

In [14]:
arr = np.array([[[1,2,3],[5,6,7]],[[8,9,10],[11,12,13]]])
print(arr)


[[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]]


# Check number of dimensions.
NumPy arrays provide the __ndim__ attribute that returns an integer that tells us how many dimensions the array have.

In [18]:
a = np.array(8)
b = np.array([[17, 2, 2007], [8, 8, 2005]])
c = np.array([8,8,2005])

print("This is a ",a.ndim,"dimensional array.")
print("This is a ", b.ndim, "dimensional array.")
print("This is a ", c.ndim, "dimensional array.")


This is a  0 dimensional array.
This is a  2 dimensional array.
This is a  1 dimensional array.


# Higher Dimensional arrays.
- An array can have any number of dimensions.
- When the array is created we can define the number of dimensions by using the __ndmin__ argument.

In [22]:
arr =np.array([1,2,3],ndmin=5)
print(arr)
print("Number of dimensions:",arr.ndim)


[[[[[1 2 3]]]]]
Number of dimensions: 5


# Access Array elements.
- We can access an array by referring to its index number.
- The indexes in NumPy arrays is similar to the lists in python.

In [24]:
arr = np.array([5,7,6])
print(arr[0])
print(arr[2])


5
6
