# NumPy
- NumPy is a python library, it is short for "Numerical Python"
- NumPy is used for working with arrays.
- NumPy was created in 2005 by __Travis Oliphant__ . It is an open source project and we can use it freely.



## Why use NumPy? 
-> In python we have lists that serve the purpose of arrays, but they are slow to process.
-> NumPy aims to provide an array object that is up to __50x__ faster than traditional Python List.
-> The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.


# Data Science 
It is the branch of computer science where we study how to store, use and analyze data for deriving information from it.


## Why is NumPy faster than list ?
- NumPy arrays are stored at one continous place in memory unlike lists, so processors can access and manipulate them very effeciently.
- This behaviour is called locality of reference in computer science
    - __In short, locality of reference is the tendency of a processor to access the same set of memory locations repetitively over a short period of time.__
- Also it is optimized to work with latest cpu architechtures.


# Which language is NumPy written in ? 
NumPy is a python library and is written partially in python, but most of the parts that require fast computation are written in C/C++


# Installatin of NumPy
Install NumPy using pip command.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Import NumPy


In [2]:
import numpy 

arr = numpy.array([1,4,3,2,8,17])
print(arr)

[ 1  4  3  2  8 17]


# NumPy as np
NumPy is usually imported under the np alias

__alias__ = In python alias are an alternate name for referring to the same thing.


In [3]:
import numpy as np

arr = np.array([12,29,2025])
print(arr)


[  12   29 2025]


## Checking NumPy version.
The version string is stored under __version__ attribute.

In [4]:
print(np.__version__)


2.4.2


# Create a NumPy nd array object
we can create a NumPy ndarray object using the array() function.

In [5]:
arr = np.array([98,45,23,11])
print(arr)
print(type(arr))


[98 45 23 11]
<class 'numpy.ndarray'>


# Dimensions in Arrays.
A dimension in arrays is one level of array depth(nested arrays).

nested arrays: arrays that have arrays as their elements.

# 0-D Arrays
0-D arrays or scalars are the elements in an array each value in an array is a 0-D array.

In [6]:
arr = np.array(17)
print(arr)


17


# 1-D Arrays
- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
- These are the most common and basic arrays.

In [7]:
arr = np.array([5,7,8,1])
print(arr)


[5 7 8 1]


# 2-D Arrays
- An array that has 1-D arrays as its elements is called a 2-D Array.
- These are often used to represent matrix or 2nd order tensors.
    - __tensors__ : In simple terms, a tensor is a mathematical object that acts as a generalized container for data. You can think of it as the "big brother" to scalars, vectors, and matrices.


In [8]:
arr = np.array([[1,2,3],[5,6,7]])
print(arr)


[[1 2 3]
 [5 6 7]]


### NumPy has a whole sub module dedicated towards matrix operations called __numpy.mat__ 


# 3-D Arrays
An array that has 2-D arrays as its elements is called 3-D array.

In [9]:
arr = np.array([[[1,2,3],[5,6,7]],[[8,9,10],[11,12,13]]])
print(arr)


[[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]]


# Check number of dimensions.
NumPy arrays provide the __ndim__ attribute that returns an integer that tells us how many dimensions the array have.

In [10]:
a = np.array(8)
b = np.array([[17, 2, 2007], [8, 8, 2005]])
c = np.array([8,8,2005])

print("This is a ",a.ndim,"dimensional array.")
print("This is a ", b.ndim, "dimensional array.")
print("This is a ", c.ndim, "dimensional array.")


This is a  0 dimensional array.
This is a  2 dimensional array.
This is a  1 dimensional array.


# Higher Dimensional arrays.
- An array can have any number of dimensions.
- When the array is created we can define the number of dimensions by using the __ndmin__ argument.

In [11]:
arr =np.array([1,2,3],ndmin=5)
print(arr)
print("Number of dimensions:",arr.ndim)


[[[[[1 2 3]]]]]
Number of dimensions: 5


# Access Array elements.
- We can access an array by referring to its index number.
- The indexes in NumPy arrays is similar to the lists in python.

In [12]:
arr = np.array([5,7,6])
print(arr[0])
print(arr[2])


5
6


# Access 2-D Arrays.
- To access elements from 2-D arrays we can use comma seperated integers representing the dimension and the index of the element.
- Think of 2-D arrays like a table with rows & columns where the dimension represents the rows and the index represents the column.

In [13]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)
print(f"3rd element on 2nd row: {arr[1,2]}")
print(f"2nd element on 1st row: {arr[0,1]}")



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3rd element on 2nd row: 8
2nd element on 1st row: 2


# Access 3-D Arrays.
To access elements from a 3-D arrays we can use comma seperated integers representing the dimensions and the index of the element.

In [14]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

print(f"2nd element on the 3rd row: {arr[1,0,1]}")


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2nd element on the 3rd row: 8


# Negative Indexing 
Use negative indexing to access an array from the end.


In [15]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

print(f"Last element from 1st row: {arr[0,-1]}")

print(f"Last element from 2nd row: {arr[1, -1]}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 1st row: 5
Last element from 2nd row: 10


# Slicing Arrays
Slicing in Python means taking elements from one give index to another given index.
- we pass slice insted of index like this: [start:end]
- we can also define the step: [start:end:step]
        by default  start=0,end=len(array),step=1

In [16]:
arr = np.array([1,4,6,12,87,90,17,8])

print(arr[2:7])

[ 6 12 87 90 17]


# Negative Slicing 
Use the minus operator to refer to an index from the end.

In [17]:
arr = np.array([3,54,65,87,11,1133,756,43,980])

print(arr[-7:-1])



[  65   87   11 1133  756   43]


# Step 
Use the step value to determine the step of the slicing


In [18]:
print(arr[-7:-1:2])


[ 65  11 756]


# Slicing 2-D arrays


In [19]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


In [20]:
# From both elements return index 3.
print(arr[0:2,3])


[4 9]


In [21]:
# From both elements, slice index 1 to 4, this will return a 2-D array.

print(arr[0:2,1:4])


[[2 3 4]
 [7 8 9]]


# Data Types in NumPy
Numpy has some extra data types and refer to data types with one character like i for integer, u for unsigned integers etc...

| i | integer           |
|---|-------------------|
| b | boolean           |
| u | unsigned integer  |
| f | float             |
| c | complex float     |
| m | timedelta         |
| M | datetime          |
| O | object            |
| S | string            |
| U | unicode string    |
| V | fixed chunk of memory for other type (void) |


# Checking the data type of an array.
The NumPy aray object has a property called __dtype__ that returns the data type of the array.


In [22]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array(["Attack on Titan","Naruto","Solo leveling","Kaiju no 8","Your Name"])
print(arr1.dtype)
print(arr2.dtype)

int64
<U15


# Creating arrays with a defined data type
We use the array() function to create arrays, this function take an optional argument dtype that allows us to define the expected data type of the array elements.


In [23]:
arr = np.array([23,43,54,],dtype="S")
print(arr)
print(arr.dtype)

# for i, u, f, s & u we can define size as well.

[b'23' b'43' b'54']
|S2


In [24]:
arr = np.array([1,2,3,4,5],dtype="i4")
print(arr)
print(arr.dtype)


[1 2 3 4 5]
int32


# What if a value can not be converted ?
If a type is given in which elements can't be casted then NumPy will raise a ValueError.


ValueError: In python it is raise whent he type of passes argument to a function is unexpected/incorrect.


In [25]:
arr = np.array(['a','b','c',],dtype='i4')
# this will raise a Value Error.


ValueError: invalid literal for int() with base 10: 'a'

# Converting data type on existing arrays
- The best way to change the data type of an existing array is to make a copy of the array with the __astype()__ method.
- The __astype()__ method creates a copy of the array and allows us to specify data type as a parameter.
- The data type can be specified using a string, like 'f' for float, 'i' for integer or we can use datatype  directly like float, int.


In [ ]:
arr = np.array([1.1,2.9,3.3])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)


[1 2 3]
int64


In [ ]:
# Changing datatype from int to boolean.
arr = np.array([0,2,17,8])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)


[False  True  True  True]
bool


# NumPy array copy vs view
- The main difference b/w a copy and a view of an array is that the copy is a new array and the view is just a view of the original array.
- The copy owns the data and any changes made to the copy will not affect original array.
- The view does not own the data and any changes made to the view will affect the original array, and vice versa.


In [ ]:
# Copy 
arr = np.array([1,2,3,4,5])

copy=arr.copy()
arr[0] = 17
print(arr)
print(copy)
# The copy should not be affected by the changes made to the original array.

[17  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# View 
view = arr.view()
arr[0] = 1
print(arr)
print(view)
# The view should be affected by the changes made to the original array.

view[-1] = 8
print(view)
print(arr)
# The original array should be affected by the changes made to the view.

[1 2 3 4 8]
[1 2 3 4 8]
[1 2 3 4 8]
[1 2 3 4 8]


# Check if array owns its data.
- As mentioned above copies owns the data and views does not own the data, but how can we check this!
- Every NumPy array has the attribute __base__ that returns __None__ if the array owns the data
- Otherwise the __base__ attribute refers to the original object.


In [ ]:
arr = np.array([1,2,3,4,5])
copy=arr.copy()
view=arr.view()

print(copy.base)
print(view.base)

# The copy returns None , the view returns the original array.

None
[1 2 3 4 5]


# Shape of an array.
The shape of an array is the number of elements in each dimension.  or in simple number of rows and column in format :   (m,n) where m=rows,n=columns

### Get the shape of an array.
NumPy arrays have an attribute called shape, that returns a tuple with each index having the number of corresponding elements.

In [ ]:
arr = np.array([[3,45,4,2,21],[87,98,1111,12311,0],[32,121,875,222,11111]])
print(arr.shape)

# The example above returns (3,5) which means that the array has 2 dimensions,
# where the first dimension has 3 elements and the second dimension has 5 elements.

# rows=3, columns=5


(3, 5)


# Creae an array with 5 dimension using __ndmin__ 
using a vector with values 1,2,3,4 and verify that last dimension has value 4

In [ ]:
arr = np.array([2,5,8,17],ndmin=5)
print(arr)
print("Shape of array:",arr.shape)

# This returns (1,1,1,1,4) which means that this array has 5 dimension,
# and the first 4 dimension has 1 element each and the last dimension has 4 elements.

[[[[[ 2  5  8 17]]]]]
Shape of array: (1, 1, 1, 1, 4)


# Reshaping Arrays.
Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
# Reshape from 1-D to 2-D , 3-D & 4-D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr1 = arr.reshape(4,3)
newarr2 = arr.reshape(2,2,3)
newarr3 = arr.reshape(4,1,1,3)

print("Reshaping into 2 dimensional array:\n",newarr1)
print("Reshaping into 3 dimensional array:\n",newarr2)
print("Reshaping into 4 dimensional array:\n",newarr3)


Reshaping into 2 dimensional array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaping into 3 dimensional array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Reshaping into 4 dimensional array:
 [[[[ 1  2  3]]]


 [[[ 4  5  6]]]


 [[[ 7  8  9]]]


 [[[10 11 12]]]]


# Can we reshape into any shape?
Yes, as long as the elements required for reshaping are equal in both shapes.


In [ ]:
# Reshaping an array with 8 elements.
arr = np.array([[1,2,3,4],[5,6,7,8]])

newarr1 = arr.reshape(2,2,2)
print(newarr1)

newrr2 = arr.reshape(5,2)
print(newarr2)

# This will raise a  ValueError.


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ValueError: cannot reshape array of size 8 into shape (5,2)

# Returns Copy or View ?


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(4,2).base)


[1 2 3 4 5 6 7 8]


## The example above returns the original array, so it is a view.

# Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number of one of the dimensions in the reshape method.

Pass __-1__ as the value, and NumPy will calculate this number for you.


In [ ]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements.
arr = np.array([1,2,3,4,5,6,7,8])

newarr = arr.reshape(2,-1,2)
print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### __Note__ : we can not pass __-1__ to more than one dimension.


# Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.


We can use __reshape(-1)__ to do this.


In [28]:
arr = np.array([[1,2,3],[4,5,9]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 9]


__Note__ : There are a lot of function for changing the shapes of arrays in numpy __flatten__, __ravel__ and also for rearranging the elements __rot90__, __flip__, __flliplr__, __flipud__, etc. These fall under intermediate to Advanced section of numpy.

# Iterating Arrays.
- Iterating means going through elements one by one.
- As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop in python.
- If we Iterate on a 1-D arrays it will go through each elements one by one.

In [29]:
arr = np.array([1,2,3,4,5])

for element in arr:
    print(element)
    

1
2
3
4
5


# Iterating 2-D Arrays.
In a 2-D array it will go through all the rows.


In [30]:
arr = np.array([[2,9,3],[8,1,4]])

for element in arr:
    print(element)
    

[2 9 3]
[8 1 4]


If we iterate on a n-D array it will go through  (n-1)th dimension one by one.

To return the actual values the scalars, we have to iterate the arrays in each dimension.

In [32]:
arr = np.array([[9,3,4],[4,5,6]])

for element in arr:
    for sub_element in element:
        print(sub_element)


9
3
4
4
5
6


# Iterating 3-D Arrays.
In a 3-D array it will goo throught all the 2-D array.


In [34]:
arr = np.array([[[4,6,7],[9,2,1]],[[87,16,10],[32,27,86]]])

for element in arr:
    print(element)
    

[[4 6 7]
 [9 2 1]]
[[87 16 10]
 [32 27 86]]


To return the actual values, Iterate the arrays.


In [35]:
for element in arr:
    for sub_element in element:
        for sub_sub_element in sub_element:
            print(sub_sub_element)

4
6
7
9
2
1
87
16
10
32
27
86


# Iterating Arrays using nditer()
The function __nditer()__ is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in Iteration. 

## Iterating on each scalar element.
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult, so in nditer() this solve that issue.

In [36]:
arr = np.array([[[4, 6,7],[9,2,1]],[[87,16,10],[32,27,86]]])

for element in np.nditer(arr):
    print(element)
    

4
6
7
9
2
1
87
16
10
32
27
86


# Iterating Array with different data types.
- We can use __op_dtypes__ args and pass it the expected datatype to change the datatype of elements while iterating.
- NumPy  does not change the data type of the element in place ( where the element is in array) so it needs some other space to perform this action that extra space is called buffer and in order to enable it in __nditer()__ we pass flags=['buffered']


In [39]:
arr = np.array([3,7,8])

for element in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(element)


np.bytes_(b'3')
np.bytes_(b'7')
np.bytes_(b'8')


# Iterating with different step size
We can use filtering and followed by iteration.


In [46]:
arr = np.array([[4,3,7],[9,22,13]])

for element in np.nditer(arr[:,::2]):
    print(element)


4
7
9
13


# Enumerated Iteration using ndenumerate()

- Enumeration means mentioning sequence number of somethings one by one.
- Sometimes we require corresponding index of the elemnt while iterating, the __ndenumerate()__ method can be used for those usecases.

In [47]:
arr = np.array([7,3,2,4,6,9])

for idx,element in np.ndenumerate(arr):
    print(f" {idx} -> {element}")

 (0,) -> 7
 (1,) -> 3
 (2,) -> 2
 (3,) -> 4
 (4,) -> 6
 (5,) -> 9


# Enumerate on 2-D Arrays elements.


In [48]:
arr = np.array([[5,3,8],[0,2,7]])

for idx,element in np.ndenumerate(arr):
    print(f"{idx} -> {element}")

(0, 0) -> 5
(0, 1) -> 3
(0, 2) -> 8
(1, 0) -> 0
(1, 1) -> 2
(1, 2) -> 7


# Joining NumPy Arrays.
- Joining means putting contents of two or more arrays in a single array.
- In SQL we join tables based on a key whereas in NumPy we join arrays be axes.
- We pass a sequence of arrays that we want to join to the __concatenate()__ function. along with the axis, if axis is not explicitly passed, it is taken as 0.

In [50]:
arr1 = np.array([3,8,7])
arr2 = np.array([9,2,5])
arr = np.concatenate((arr1,arr2))

print(arr)


[3 8 7 9 2 5]


# Join two 2-D arrays along rows(axis=1)


In [53]:
arr1 = np.array([[87,43,33],[12,21,11]])

arr2 = np.array([[32,23,33],[87,78,77]])

print("Concatenating along rows:")
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)
print("Default concatenation:")
arr3= np.concatenate((arr1,arr2))
print(arr3)


Concatenating along rows:
[[87 43 33 32 23 33]
 [12 21 11 87 78 77]]
Default concatenation:
[[87 43 33]
 [12 21 11]
 [32 23 33]
 [87 78 77]]


# Joining arrays using stack functions.
- Stacking is same as concatenation the only difference is that stacking is done along a new axis.
- We concatenate two 1-D arrays along the second axis which would result in putting them one over the other , i.e stacking
- We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [ ]:
arr1 = np.array([3, 8, 7])
arr2 = np.array([9, 2, 5])

print("Along axis=0")
arr = np.stack((arr1, arr2))
print(arr)

print("ALong axis=1")
arr = np.stack((arr1,arr2),axis=1)
print(arr)

Along axis=0
[[3 8 7]
 [9 2 5]]
ALong axis=1
[[3 9]
 [8 2]
 [7 5]]


# Stacking along Rows & Columns
- hstack() = to stack along rows.
- vstack() = to stack along columns.

In [62]:
arr1 = np.array([3, 8, 7])
arr2 = np.array([9, 2, 5])

print("Along Rows:")
arr = np.hstack((arr1,arr2))
print(arr)

print("Along Columns:")
arr = np.vstack((arr1,arr2))
print(arr)


Along Rows:
[3 8 7 9 2 5]
Along Columns:
[[3 8 7]
 [9 2 5]]


# Stacking  along height(depth)

- dstack() = to stack along height which is the same as depth.


In [63]:
arr1 = np.array([3, 8, 7])
arr2 = np.array([9, 2, 5])

arr = np.dstack((arr1,arr2))
print(arr)


[[[3 9]
  [8 2]
  [7 5]]]


# NumPy splitting array.
- splitting is reverse operation of joining.
- joining merges multiple arrays into one and splitting breaks one array into multiple.

- We use __array_split()__ for splitting arrays, we pass it the array we want to split and the number of splits.

In [65]:
arr = np.array([1,9,54])

newarr = np.array_split(arr,3)
print(newarr)

[array([1]), array([9]), array([54])]


### Note:
The return value is a list containing three arrays.


### If the array has less elements then required it will adjust from the end accordingly.

In [68]:
arr = np.array([8,4,3,2,1,0])

newarr= np.array_split(arr,4)
print(newarr)

[array([8, 4]), array([3, 2]), array([1]), array([0])]


### Note:
We also have the method __split()__ available but it will not adjust the elements when elements are less in source array for splitting.

# Splitting into array.
The return value of the __array_split()__ method is an array containing each of the split as an array.

If we split an array into 3 arrays we can access them from the result just like an array element.


In [72]:
arr = np.array([8, 4, 3, 2, 1, 9])

newarr = np.array_split(arr, 4)
print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])


[8 4]
[3 2]
[1]
[9]


# Splitting 2-D Arrays.
- Use the __array_split()__ method pass in the array 

In [74]:
arr = np.array([[7,5],[8,1],[0,0],[3,11],[23,32]])

newarr = np.array_split(arr,3)
print(newarr)


[array([[7, 5],
       [8, 1]]), array([[ 0,  0],
       [ 3, 11]]), array([[23, 32]])]


### In addition we can specify which axis we want to do the split around.

In [82]:
arr = np.array([[7, 5], [8, 1], [0, 0], [3, 11], [23, 32]])
print("""Splitting 2-D array along the column(axis=1)""")
newarr=np.array_split(arr,2,axis=1)
print(newarr)

print("""Splitting 2-D array along the column(axis=1)
when there are less elements than splitting expects. """)
newarr = np.array_split(arr, 3,axis=1)
print(newarr)

Splitting 2-D array along the column(axis=1)
[array([[ 7],
       [ 8],
       [ 0],
       [ 3],
       [23]]), array([[ 5],
       [ 1],
       [ 0],
       [11],
       [32]])]
Splitting 2-D array along the column(axis=1)
when there are less elements than splitting expects. 
[array([[ 7],
       [ 8],
       [ 0],
       [ 3],
       [23]]), array([[ 5],
       [ 1],
       [ 0],
       [11],
       [32]]), array([], shape=(5, 0), dtype=int64)]


### An alternative solution is using hsplit(), vsplit(), dsplit() opposite of theri respective.

In [92]:
arr = np.array([[7, 5], [8, 1], [0, 0], [3, 11], [23, 32]])

arr_h = np.hsplit(arr,2)
arr_v = np.vsplit(arr,5)

print("Hsplit:")
print(arr_h)
print("Vsplit:")
print(arr_v)

Hsplit:
[array([[ 7],
       [ 8],
       [ 0],
       [ 3],
       [23]]), array([[ 5],
       [ 1],
       [ 0],
       [11],
       [32]])]
Vsplit:
[array([[7, 5]]), array([[8, 1]]), array([[0, 0]]), array([[ 3, 11]]), array([[23, 32]])]


# NumPy Searching Arrays.
We can search an array for a certain value, and return the indexes that get a match.

To search an array we use the __where()__  method.

In [96]:
arr = np.array([4,7,9,2,0,])

newarr = np.where(arr==0)
print(newarr)

newarr = np.where(arr==9)
print(newarr)


(array([4]),)
(array([2]),)


In [99]:
# Find the Indexes where the values are even.
arr = np.array([4, 7, 9, 2, 10,])

newarr = np.where(arr%2 == 0)
print(newarr)


(array([0, 3, 4]),)


# Search sorted.
There is a method called __search_sorted()__  which performs a binary search in array and returns the index where the specified value be inserted to maintain the search order.

- __searchsorted()__

In [102]:
arr = np.array([4,58,78,99])

newarr = np.searchsorted(arr,67)
print(newarr)

2


# Search from the right side.
By default the left most index is returned but we can give side = 'right' to return the right most index instead.

In [104]:
arr = np.array([4, 58, 78, 99])

newarr = np.searchsorted(arr, 79,side='right')
print(newarr)

3


# Multiple Values.
To search for more than one value, use an array with the specified value.


In [105]:
arr = np.array([4, 58, 78, 99])

newarr = np.searchsorted(arr,[79,2,10001])
print(newarr)

[3 0 4]


# Sorting Arrays.
- Sorting means putting elements in an ordered sequence.
- Ordered sequence is any sequence, that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
- The NumPy ndarray object has a function called __sort()__ that will sort a specified array.


In [107]:
arr = np.array([3,87,1,0,9898])
print(np.sort(arr))


[   0    1    3   87 9898]


### Note:
This method returns a copy of the array leaving the original array unchanged.

# Sorting a 2-D Array.
If we use sort() method on 2-D array both arrays wil be sorted.

In [108]:
arr = np.array([[7,19,9],[0,67,1]])

print(np.sort(arr))

[[ 7  9 19]
 [ 0  1 67]]


# NumPy Filter Array.
- Filtering Arrays:
    Getting some elements out of an existing array and creating a new array out of them is called filtering.
- In NumPy we filter an array using a boolean index list.
- A boolean index list is a list of booleans corresponding to indexes in the array.
- If the value at an index in __True__ that element is contained in the filtered array if the value at that index is __False__ that element is excluded from the filtered array.


In [109]:
arr = np.array([65,33,11,23,45,77])

lst = [True,False,False,True,True,False]

newarr = arr[lst]

print(newarr)



[65 23 45]


# Creating the Filter Array.
The common use is to create a filter array based on conditions.


In [ ]:
arr = np.array([65, 33,11,23,45,77])
lst=[]

for i in arr:
    if i%11 != 0:
        lst.append(True)
    else:
        lst.append(False)

newarr = arr[lst]

print(newarr)



IndexError: boolean index did not match indexed array along axis 0; size of axis is 6 but size of corresponding boolean axis is 9