# NumPy
- NumPy is a python library, it is short for "Numerical Python"
- NumPy is used for working with arrays.
- NumPy was created in 2005 by __Travis Oliphant__ . It is an open source project and we can use it freely.



## Why use NumPy? 
-> In python we have lists that serve the purpose of arrays, but they are slow to process.
-> NumPy aims to provide an array object that is up to __50x__ faster than traditional Python List.
-> The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.


# Data Science 
It is the branch of computer science where we study how to store, use and analyze data for deriving information from it.


## Why is NumPy faster than list ?
- NumPy arrays are stored at one continous place in memory unlike lists, so processors can access and manipulate them very effeciently.
- This behaviour is called locality of reference in computer science
    - __In short, locality of reference is the tendency of a processor to access the same set of memory locations repetitively over a short period of time.__
- Also it is optimized to work with latest cpu architechtures.


# Which language is NumPy written in ? 
NumPy is a python library and is written partially in python, but most of the parts that require fast computation are written in C/C++


# Installatin of NumPy
Install NumPy using pip command.

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Import NumPy


In [3]:
import numpy 

arr = numpy.array([1,4,3,2,8,17])
print(arr)

[ 1  4  3  2  8 17]


# NumPy as np
NumPy is usually imported under the np alias

__alias__ = In python alias are an alternate name for referring to the same thing.


In [4]:
import numpy as np

arr = np.array([12,29,2025])
print(arr)


[  12   29 2025]


## Checking NumPy version.
The version string is stored under __version__ attribute.

In [5]:
print(np.__version__)


2.4.2


# Create a NumPy nd array object
we can create a NumPy ndarray object using the array() function.

In [6]:
arr = np.array([98,45,23,11])
print(arr)
print(type(arr))


[98 45 23 11]
<class 'numpy.ndarray'>


# Dimensions in Arrays.
A dimension in arrays is one level of array depth(nested arrays).

nested arrays: arrays that have arrays as their elements.

# 0-D Arrays
0-D arrays or scalars are the elements in an array each value in an array is a 0-D array.

In [7]:
arr = np.array(17)
print(arr)


17


# 1-D Arrays
- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
- These are the most common and basic arrays.

In [8]:
arr = np.array([5,7,8,1])
print(arr)


[5 7 8 1]


# 2-D Arrays
- An array that has 1-D arrays as its elements is called a 2-D Array.
- These are often used to represent matrix or 2nd order tensors.
    - __tensors__ : In simple terms, a tensor is a mathematical object that acts as a generalized container for data. You can think of it as the "big brother" to scalars, vectors, and matrices.


In [9]:
arr = np.array([[1,2,3],[5,6,7]])
print(arr)


[[1 2 3]
 [5 6 7]]


### NumPy has a whole sub module dedicated towards matrix operations called __numpy.mat__ 


# 3-D Arrays
An array that has 2-D arrays as its elements is called 3-D array.

In [10]:
arr = np.array([[[1,2,3],[5,6,7]],[[8,9,10],[11,12,13]]])
print(arr)


[[[ 1  2  3]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]]


# Check number of dimensions.
NumPy arrays provide the __ndim__ attribute that returns an integer that tells us how many dimensions the array have.

In [11]:
a = np.array(8)
b = np.array([[17, 2, 2007], [8, 8, 2005]])
c = np.array([8,8,2005])

print("This is a ",a.ndim,"dimensional array.")
print("This is a ", b.ndim, "dimensional array.")
print("This is a ", c.ndim, "dimensional array.")


This is a  0 dimensional array.
This is a  2 dimensional array.
This is a  1 dimensional array.


# Higher Dimensional arrays.
- An array can have any number of dimensions.
- When the array is created we can define the number of dimensions by using the __ndmin__ argument.

In [12]:
arr =np.array([1,2,3],ndmin=5)
print(arr)
print("Number of dimensions:",arr.ndim)


[[[[[1 2 3]]]]]
Number of dimensions: 5


# Access Array elements.
- We can access an array by referring to its index number.
- The indexes in NumPy arrays is similar to the lists in python.

In [13]:
arr = np.array([5,7,6])
print(arr[0])
print(arr[2])


5
6


# Access 2-D Arrays.
- To access elements from 2-D arrays we can use comma seperated integers representing the dimension and the index of the element.
- Think of 2-D arrays like a table with rows & columns where the dimension represents the rows and the index represents the column.

In [15]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)
print(f"3rd element on 2nd row: {arr[1,2]}")
print(f"2nd element on 1st row: {arr[0,1]}")



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3rd element on 2nd row: 8
2nd element on 1st row: 2


# Access 3-D Arrays.
To access elements from a 3-D arrays we can use comma seperated integers representing the dimensions and the index of the element.

In [16]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

print(f"2nd element on the 3rd row: {arr[1,0,1]}")


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2nd element on the 3rd row: 8


# Negative Indexing 
Use negative indexing to access an array from the end.


In [19]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

print(f"Last element from 1st row: {arr[0,-1]}")

print(f"Last element from 2nd row: {arr[1, -1]}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 1st row: 5
Last element from 2nd row: 10


# Slicing Arrays
Slicing in Python means taking elements from one give index to another given index.
- we pass slice insted of index like this: [start:end]
- we can also define the step: [start:end:step]
        by default  start=0,end=len(array),step=1

In [20]:
arr = np.array([1,4,6,12,87,90,17,8])

print(arr[2:7])

[ 6 12 87 90 17]


# Negative Slicing 
Use the minus operator to refer to an index from the end.

In [22]:
arr = np.array([3,54,65,87,11,1133,756,43,980])

print(arr[-7:-1])



[  65   87   11 1133  756   43]


# Step 
Use the step value to determine the step of the slicing


In [23]:
print(arr[-7:-1:2])


[ 65  11 756]


# Slicing 2-D arrays


In [24]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


In [26]:
# From both elements return index 3.
print(arr[0:2,3])


[4 9]


In [27]:
# From both elements, slice index 1 to 4, this will return a 2-D array.

print(arr[0:2,1:4])


[[2 3 4]
 [7 8 9]]


# Data Types in NumPy
Numpy has some extra data types and refer to data types with one character like i for integer, u for unsigned integers etc...

| i | integer           |
|---|-------------------|
| b | boolean           |
| u | unsigned integer  |
| f | float             |
| c | complex float     |
| m | timedelta         |
| M | datetime          |
| O | object            |
| S | string            |
| U | unicode string    |
| V | fixed chunk of memory for other type (void) |


# Checking the data type of an array.
The NumPy aray object has a property called __dtype__ that returns the data type of the array.


In [28]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array(["Attack on Titan","Naruto","Solo leveling","Kaiju no 8","Your Name"])
print(arr1.dtype)
print(arr2.dtype)

int64
<U15


# Creating arrays with a defined data type
We use the array() function to create arrays, this function take an optional argument dtype that allows us to define the expected data type of the array elements.


In [ ]:
arr = np.array([23,43,54,],dtype="S")
print(arr)
print(arr.dtype)

# for i, u, f, s & u we can define size as well.

[b'23' b'43' b'54']
|S2


In [31]:
arr = np.array([1,2,3,4,5],dtype="i4")
print(arr)
print(arr.dtype)


[1 2 3 4 5]
int32


# What if a value can not be converted ?
If a type is given in which elements can't be casted then NumPy will raise a ValueError.


ValueError: In python it is raise whent he type of passes argument to a function is unexpected/incorrect.


In [33]:
arr = np.array(['a','b','c',],dtype='i4')
# this will raise a Value Error.


ValueError: invalid literal for int() with base 10: 'a'

# Converting data type on existing arrays
- The best way to change the data type of an existing array is to make a copy of the array with the __astype()__ method.
- The __astype()__ method creates a copy of the array and allows us to specify data type as a parameter.
- The data type can be specified using a string, like 'f' for float, 'i' for integer or we can use datatype  directly like float, int.


In [35]:
arr = np.array([1.1,2.9,3.3])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)


[1 2 3]
int64


In [ ]:
# Changing datatype from int to boolean.
arr = np.array([0,2,17,8])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)


TypeError: order must be str, not type